### ISSUE TITLE
pip install --user should use "pip3" when available

### ISSUE THREAD

**Issue by EricR86** [raghur/vim-ghost#10]
This is a minor environment issue but for users who have to manage both version of python on their system (say an old Python 2 system install for yum, etc), using pip3 if it is available would seem like a better choice when attempting to install the requirements. 'pip' may alias by default to the python 2 version.

**Comment by raghur** [comment]
So the install script uses
https://github.com/raghur/vim-ghost/blob/5dc053ba72deaa78f34a894d5a39478ee53b166e/install#L2

Basically if python3 exists, it uses the pip corresponding to whatever version of python3 is being used by nvim. I earlier had `pip3` but this ran into issues where there might be multiple python3 versions around and pip pointing to a different one from whatever is python3 version under nvim. See 
https://github.com/raghur/vim-ghost/issues/6#issuecomment-371043021

**Comment by EricR86** [comment]
My mistake. I did have an issue with `:GhostInstall` not installing the dependencies though and now I have no idea what caused it. I assumed it was because of the 'pip' command mentioned on the README.
