### ISSUE TITLE
Errors when installing on Ubuntu

### ISSUE THREAD

**Issue by j127** [raghur/vim-ghost#12]
Thanks for the great plugin.

When installing on Ubuntu 16.04, it was generating errors until I installed two Python packages with `sudo`:

```
$ sudo pip install python-slugify
```

And this one: https://github.com/dpallot/simple-websocket-server.git

It might be useful to add that to the installation instructions (or an alternate installation method that doesn't require `sudo`).

**Comment by raghur** [comment]
can you tell me what errors you get?

The installation process installs those two plugins without `sudo` (`pip install --user`) installs.

**Comment by j127** [comment]
When I did `:GhostInstall`, it showed errors about those two packages' not being found.

Maybe it has something to do with my computer, since I don't think `--user` has worked with another package either. If no one else sees the problem, then you can close the issue.
