### ISSUE TITLE
Tips/thoughts on using this for MacVim?

### ISSUE THREAD

**Issue by deinspanjer** [raghur/vim-ghost#13]
I fought with the tcl (ugh) script for a while, but especially because OSX is using an older version of tcl, it was a pain.

I haven't touched NeoVim to-date, so I'm just wondering if it would be significant effort to get this method running in normal vim / MacVim?  I saw in the readme that vim compatibility is a to-do, and I'll do some research on it a bit later, but thought I'd toss this issue in to see if someone else has a quick answer.

**Comment by raghur** [comment]
A few things off the top of my head:
1. You'd probably need a shim like vim-hug-neovim-rpc. 
2. bringing window to focus depends on OS specific tools - pywinauto on windows and xdotool on linux.

**Comment by deinspanjer** [comment]
Okay, I actually took this as the nudge I needed to try out NeoVim and I'm pretty happy with it so far. :)
