### ISSUE TITLE
Where to install

### ISSUE THREAD

**Issue by stappersg** [raghur/vim-ghost#23]
The
```
2. Add this plugin
|   "  Vim-plug
|   Plug 'raghur/vim-ghost', {'do': ':GhostInstall'}
```
is too short. At least for me.

What I miss is where to install. I don't known what the **full path** should be.

Probably `$NEOVIM_PLUGIN_PATH/vim-ghost` or `$NEOVIM_PLUGIN_PATH/raghur/vim-ghost`

And I don't even know if there is such a thing as a `$NEOVIM_PLUGIN_PATH` and the value of it.

**Comment by raghur** [comment]
Are you using [vim-plug](https://github.com/junegunn/vim-plug)? `Plug` is a command added by vim-plug and if you head over to vim plug home page, you can see configuration examples of setting the base dir for plugins to be downloaded to.

**Comment by stappersg** [comment]
The https://github.com/junegunn/vim-plug/wiki/tutorial  was a real eye opener for me. Thanks.

**Comment by stappersg** [comment]
Quoting https://github.com/junegunn/vim-plug/wiki/tutorial

> A Vim plugin is a set of Vimscript files that are laid out in a certain directory structure. Before plugin managers became popular, Vim plugins were usually distributed as tarballs. Users would manually download the file and extract it in a single directory called ~/.vim, and Vim would load the files under the directory during startup.

That in my words: _There is a whole  ecosystem to extend vim._

An ecosystem I didn't know that it exists.

More text from https://github.com/junegunn/vim-plug/wiki/tutorial

> vim-plug, a modern Vim plugin manager, downloads plugins into separate directories for you and makes sure that they are loaded correctly. 

> All you have to do is to download the file in a directory so that Vim can load it.

That in my words: _vim-plug is like the legendary horse that made to conquest of Troy possible._


Thing that I'm looking for is how to install vim-ghost  without a plugin manager.


Happy New Year.
