### ISSUE TITLE
Incompatibility with neoclide/coc.nvim

### ISSUE THREAD

**Issue by doronbehar** [raghur/vim-ghost#28]
To complement https://github.com/neoclide/coc.nvim/issues/245, I thought the matter should be reported here as well.

To summarize: When both plugins are installed, coc.nvim doesn't work.

I don't use a plugin manager like [junegunn/vim-plug](https://github.com/junegunn/vim-plug) and I use the native `pack` directories layout. Even if `vim-ghost` is installed in `pack/*/opt/` and not in `pack/*/start/` and I run `packadd vim-ghost` after Neovim is started, I get the error `[coc.nvim] server connection lost`.

**Comment by oblitum** [comment]
The coc.nvim counterpart seems ongoing and author claimed to have found the cause, it should be possibly fixed on next release. Seems like this one may be closed (it's not that it hasn't been useful, other people searching may hit here).

**Comment by raghur** [comment]
@doronbehar and @oblitum thank you both. I was going to comment that it was going to take me some time to get to this -but am glad that it's been RC'ed.

**Comment by doronbehar** [comment]
https://github.com/neoclide/coc.nvim/issues/245 was fixed a long time ago so I think this can be closed as well.
