### ISSUE TITLE
Buffer is unexpectedly deleted when Firefox crashes

### ISSUE THREAD

**Issue by Celti** [raghur/vim-ghost#3]
I just lost a great deal of work — the local buffer in (Neo)Vim had been saved, but I hadn't submitted the textbox in Firefox when a bit of research in another tab brought down the entire browser. I was *not* expecting Firefox crashing to delete data in Vim — no other external editing extension I've used has operated that way (and I've switched back to withExEditor for the moment, even though it's rather more inconvenient).

Is there anything that can be done to avoid this, or is it an issue with GhostText itself, and not the way the Vim plugin is written?

**Comment by raghur** [comment]
Sorry to hear that. The buffer is deleted when the browser plugin disconnects the tab. The buffer is closed and the temp file deleted - 
https://github.com/raghur/vim-ghost/blob/c19a89d97d8d43d14a01cc8304c13cc957bb2ece/rplugin/python3/ghost.py#L233

Leaving the temp file around results in littering tmp.. however, I can make this a plugin option.

There's really not much I can do - I'm guessing that whatever happened in the browser caused it to close/shutdown and that in turn triggered a disconnect.

**Comment by Celti** [comment]
An option to disable automatically closing the buffer on disconnect and defer removing the temp file until the buffer is closed would be very nice, yes. I don't know much Python but I'll take a stab at implementing that myself when I have some time.

**Comment by Celti** [comment]
I actually think I may have found a best-of-both-worlds resolution; simply don't *unconditionally* delete the buffer (i.e., call `:bdelete` and not `:bdelete!`), and move the temp-file cleanup within the `try` block so that it doesn't get cleaned up out from under an unsaved buffer.

At least on Firefox, GhostText doesn't close the WebSocket itself unless the entire browser closes/crashes, so the *only* visible change in behaviour here is that if the browser closes and you have not saved the buffer in nvim, it will remain open and the tempfile will remain on the filesystem. If you know you can afford to lose that buffer, then, well, why *haven't* you saved it?

**Comment by raghur** [comment]
>At least on Firefox, GhostText doesn't close the WebSocket itself unless the entire browser closes/crashes, so the only visible change in behaviour here is that if the browser closes and you have not saved the buffer in nvim, it will remain open and the tempfile will remain on the filesystem. If you know you can afford to lose that buffer, then, well, why haven't you saved it?

So let me make sure I understand - if the buffer is saved and the ws message sent, but for whatever reason the browser plugin does not update the browser text area (or does and browser crashed right afterwards). In this case, wouldn't the buffer be deleted (:bdelete) and also removed (os.remove)? If that's the case, then the user isn't served well.
