### ISSUE TITLE
Latest commit breaks vim-ghost (neovim, linux)

### ISSUE THREAD

**Issue by jared-w** [raghur/vim-ghost#30]
* neovim version: 0.3.2-dev (from the unstable ppa for ubuntu).
    Have also tested with the nvim-git package on the AUR.
* python version: 3.6.7

`:GhostInstall` works correctly and the logs have no errors;
however, clicking the button in the browser does nothing but highlight the textarea.
I did test this with setting explicit `g:ghost_port` and `g:ghost_cmd` and without; tested it with VSCode and in vim with a minimal vimrc consisting of only the plugin.

I narrowed this down to the latest commit; I'm unsure of where to look in the commit, unfortunately.

Currently I've set the commit manually in my `init.vim` to work around this:

```vim
Plug 'raghur/vim-ghost', {'commit': '672d1052425cc9dd8f5f56ba31732f0637b95caa', 'do': ':GhostInstall'}
```

**Comment by raghur** [comment]
@jared-w Thanks for the bug report :+1:  Just pushed a fix.
