### ISSUE TITLE
Installing automatic filetype and autofocus

### ISSUE THREAD

**Issue by Yemeen** [raghur/vim-ghost#41]
I don't quite understand what I should be doing with the commands you provide in the readme to make the filetype automatic based on website. Similarly for the Mac instructions of autofocus. Could you explain a bit more?

Thank you!

**Comment by raghur** [comment]
filetype: Copy the readme example to your vim init script  and then tweak the regular expression for whichever website you want

about mac config - Please see the documentation file for more details. I don't use a mac myself and the bit was contributed by somebody so I don't know much.
