### ISSUE TITLE
Undefined variable error on start up

### ISSUE THREAD

**Issue by Yemeen** [raghur/vim-ghost#42]
<img width="704" alt="Screen Shot 2020-11-04 at 4 00 50 PM" src="https://user-images.githubusercontent.com/11223834/98167558-41fed400-1eb7-11eb-97c6-7d73dafb896c.png">

**Comment by raghur** [comment]
Looks like you're on vim. Do you have yarp installed?

**Comment by Yemeen** [comment]
Do you mean [this](https://github.com/SpaceVim/nvim-yarp)?

**Comment by Yemeen** [comment]
Got [ghost-text.vim](https://github.com/pandysong/ghost-text.vim) to work instead. Thanks anyways!

**Comment by tecfu** [comment]
The error message is because vim-ghost depends on the following nvim plugin: https://github.com/SpaceVim/nvim-yarp

To fix the issue using vim-plug:

```
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'SpaceVim/nvim-yarp'
Plug 'raghur/vim-ghost'
```
